name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docodile
        run: make build
      - name: Run Docodile build
        run: ./src/build/docodile build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          external_repository: docodile/docodile.github.io
          publish_dir: ./site
          publish_branch: main
